[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
    "python3 -m pip install -r requirements.txt --break-system-packages",
    "python3 -m playwright install --with-deps chromium"
]

[start]
cmd = "python bot.py"
